// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkoXRAYaFn7AIx6NvHK0uBsTaj02N1mw',
    appId: '1:1022168436528:web:fc79bea17b84d7756ec2f5',
    messagingSenderId: '1022168436528',
    projectId: 'rdp-todo-e1f64',
    authDomain: 'rdp-todo-e1f64.firebaseapp.com',
    storageBucket: 'rdp-todo-e1f64.firebasestorage.app',
    measurementId: 'G-FCRSYXCJGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhXq5CGqLmYprxo4l6skviy5O8fGeCvA',
    appId: '1:1022168436528:android:c567a22d7d6debff6ec2f5',
    messagingSenderId: '1022168436528',
    projectId: 'rdp-todo-e1f64',
    storageBucket: 'rdp-todo-e1f64.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRkoXRAYaFn7AIx6NvHK0uBsTaj02N1mw',
    appId: '1:1022168436528:web:6413ee10c27560126ec2f5',
    messagingSenderId: '1022168436528',
    projectId: 'rdp-todo-e1f64',
    authDomain: 'rdp-todo-e1f64.firebaseapp.com',
    storageBucket: 'rdp-todo-e1f64.firebasestorage.app',
    measurementId: 'G-9FV6K41DES',
  );
}
